language: ruby
rvm:
  - 2.4.1
services:
  - postgresql
addons:
  postgresql: 9.6
env:
  global:
    - CC_TEST_REPORTER_ID=a3be7f7e518ebe5830293ad0074d606bba62df942679ee11e210e25ed749cf3b
    - CT_URL=http://localhost:9000
    - CT_TOKEN=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ
    - API_VERSION=v1
    - LOCAL_URL=http://localhost:3000
    - RAILS_ENV=test
    - SECRET_KEY_BASE=secret
    - RW_API_URL=https://api.resourcewatch.org
    - APIGATEWAY_URL=https://production-api.globalforestwatch.org

before_script:
  - RAILS_ENV=test bundle exec rake db:drop db:create db:schema:load
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - bundle exec rspec spec --fail-fast

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
