version: '2'
services:
  postgres:
    image: postgres
    volumes:
      - "./.data/db:/var/lib/postgresql/data"
  api:
    build: .
    command: 'bash -c ''bundle exec puma -C config/puma.rb'''
    ports:
      - "3001:3000"
    env_file: .env
    environment:
      - RAILS_ENV=production
      - RACK_ENV=production
    links:
      - postgres
    container_name: rw
    volumes:
      - "./public/system:/usr/src/app/public/system"
      - "./public/uploads:/usr/src/app/public/uploads"
