version: '3'
services:
  test:
    build: .
    command: test
    ports:
      - "3001:3000"
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_USER: postgres
      POSTGRES_PASS: postgres
      POSTGRES_DATABASE: postgres
      SECRET: keyboard cat
      RAILS_ENV: test
      RACK_ENV: test
      WAIT_HOSTS: postgres:5432
      MICROSERVICE_TOKEN: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6Im1pY3Jvc2VydmljZSIsImNyZWF0ZWRBdCI6IjIwMTYtMDktMTQifQ.IRCIRm1nfIQTfda_Wb6Pg-341zhV8soAgzw7dd5HxxQ
      GATEWAY_URL: http://localhost:9000
      AWS_REGION: "us-east-1"
      S3_AWS_ACCESS_KEY_ID: "test"
      S3_AWS_SECRET_ACCESS_KEY: "test"
    depends_on:
      - postgres
    container_name: rw

  postgres:
    image: postgres:9.6.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: resource-watch-manager-test
    ports:
      - "5432"
