version: '2'
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    volumes:
      - "./data/db:/var/lib/postgresql"
  web:
    build: .
    ports:
      - "6000:3000"
    env_file: .env
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
    container_name: resourcewatch-manager
    links:
      - db
    depends_on:
      - db
    volumes:
      - ".:/usr/src/resourcewatch-manager"
