version: '2'
services:
  postgres:
    image: postgres
    volumes:
      - "./.data/db:/var/lib/postgresql/data"
  web:
    build: .
    command: 'bash -c ''bundle exec puma -C config/puma.rb'''
    ports:
      - "6000:3000"
    env_file: .env
    environment:
      - RAILS_ENV=production
      - RACK_ENV=production
      - DATABASE_URL=postgres://postgres@postgres/rw_manager_prod
    container_name: resourcewatch-manager
    links:
      - postgres
    volumes:
      - "./public/system:/usr/src/resourcewatch-manager/public/system"
