version: '3'
services:
  test:
    build: .
    command: test
    ports:
      - "3001:3000"
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=postgres
      - POSTGRES_PASS=postgres
      - POSTGRES_DATABASE=postgres
      - SECRET=keyboard cat
      - BULLET=enabled
      - RAILS_ENV=test
      - RACK_ENV=test
      - WAIT_HOSTS=postgres:5432
    depends_on:
      - postgres
    container_name: rw

  postgres:
    image: postgres:9.6.2
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432"
