version: '2'
services:
  database:
    image: postgres
    volumes:
      - "./data/db:/var/lib/postgresql/data"
  web:
    build: .
    command: 'bash -c ''bundle exec puma -C config/puma.rb'''
    ports:
      - "6000:3000"
    env_file: .env
    environment:
      - POSTGRES_HOST=database
      - POSTGRES_USER=postgres
    container_name: resourcewatch-manager
    links:
      - database
    volumes:
      - "./public/system:/usr/src/resourcewatch-manager/public/system"
