apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: {name}
  name: {name}
spec:
  revisionHistoryLimit: 0
  template:
    metadata:
      annotations:
        chaos.alpha.kubernetes.io/enabled: "true"
      labels:
        name: {name}
    spec:
      containers:
      - name: {name}
        image: vizzuality/{name}
        imagePullPolicy: Always
        args:
          - start
        resources:
          requests:
            memory: "0Mi"
            cpu: "0m"
        env:
          - name: APIGATEWAY_URL
            value: "https://api.resourcewatch.org"
          - name: RW_API_URL
            value: "https://api.resourcewatch.org"
          - name: RAILS_SERVE_STATIC_FILES
            value: "true"
          - name: DATABASE_URL
            valueFrom:
                secretKeyRef:
                  name: dbsecrets
                  key: RESOURCE_WATCH_MANAGER_POSTGRESDB
        ports:
          - containerPort: 3000
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /healthz
            port: 3000
          initialDelaySeconds: 30
          timeoutSeconds: 5
          periodSeconds: 15
      restartPolicy: Always
