apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    name: {name}-staging
  name: {name}-staging
spec:
  revisionHistoryLimit: 0
  template:
    metadata:
      labels:
        name: {name}-staging
    spec:
      containers:
      - name: {name}-staging
        image: vizzuality/{name}
        imagePullPolicy: Always
        args:
          - start
        resources:
          requests:
            memory: "0Mi"
            cpu: "0m"
        env:
          - name: CONTACT_EMAIL
            value: "santos.tiago@gmail.com"
          - name: SENDGRID_DOMAIN
            value: "vizzuality.com"
          - name: SENDGRID_USERNAME
            valueFrom:
                secretKeyRef:
                  name: appsecrets
                  key: RW_SENDGRID_USERNAME
          - name: SENDGRID_PASSWORD
            valueFrom:
                secretKeyRef:
                  name: appsecrets
                  key: RW_SENDGRID_PASSWORD
          - name: RAILS_LOG_TO_STDOUT
            value: "true"
          - name: APIGATEWAY_URL
            value: "https://api.resourcewatch.org"
          - name: RW_API_URL
            value: "https://api.resourcewatch.org"
          - name: RAILS_SERVE_STATIC_FILES
            value: "true"
          - name: DATABASE_URL
            valueFrom:
                secretKeyRef:
                  name: dbsecrets
                  key: RESOURCE_WATCH_MANAGER_POSTGRESDB_STAGING
          - name: S3_BUCKET_NAME
            value: "wri-api-backups"
          - name: S3_PATH
            value: "resourcewatch/test"
          - name: AWS_REGION
            value: "us-east-1"
          - name: AWS_ACCESS_KEY_ID
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: S3_ACCESS_KEY_ID
          - name: AWS_SECRET_ACCESS_KEY
            valueFrom:
                secretKeyRef:
                  name: mssecrets
                  key: S3_SECRET_ACCESS_KEY
        ports:
          - containerPort: 3000
      restartPolicy: Always
