apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: rw
  name: resource-watch-manager
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: resource-watch-manager
  minReplicas: 2
  maxReplicas: 12
  targetCPUUtilizationPercentage: 50
