apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  namespace: rw
  name: {name}
spec:
  scaleTargetRef:
    apiVersion: apps/v1beta1
    kind: Deployment
    name: {name}
  minReplicas: 2
  maxReplicas: 12
  targetCPUUtilizationPercentage: 50
