apiVersion: v1
kind: Service
metadata:
  namespace: rw
  labels:
    name: resource-watch-manager
  name: resource-watch-manager
spec:
  ports:
    - name: http
      protocol: TCP
      port: 3000
      targetPort: 3000
  selector:
    name: resource-watch-manager

